# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=0.1.1
maven_group=net.fawnoculus
archives_base_name=Vanilla-Backrooms

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.138.4+1.21.10

polymer_version=0.14.4+1.21.10

modmenu_version=16.0.0
sodium_version=mc1.21.10-0.7.3-fabric

rei_version=21.9.813
architectury_version=18.0.8
cloth_config_version=20.0.149
