# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Mod Properties
mod_version=0.2.0
maven_group=net.fawnoculus.vanilla_backrooms
archives_base_name=Vanilla-Backrooms
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Fabric API
fabric_api_version=0.155.2+26.2
polymer_version=0.17.3+26.2
