package net.fawnoculus.vanilla_backrooms.client.datagen.loot;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableProvider;
import net.fawnoculus.vanilla_backrooms.items.ModItems;
import net.fawnoculus.vanilla_backrooms.items.custom.LevelKeyItem;
import net.fawnoculus.vanilla_backrooms.misc.ModLootTables;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.loot.function.*;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.Potion;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.EmptyLootItem;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.EnchantRandomlyFunction;
import net.minecraft.world.level.storage.loot.functions.EnchantWithLevelsFunction;
import net.minecraft.world.level.storage.loot.functions.SetCustomDataFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.functions.SetPotionFunction;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.function.BiConsumer;

public class ChestLootTableProvider extends SimpleFabricLootTableProvider {
    private final CompletableFuture<HolderLookup.Provider> registryLookup;

    public ChestLootTableProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(output, registryLookup, LootContextParamSets.CHEST);

        this.registryLookup = registryLookup;
    }

    @Override
    public void generate(BiConsumer<ResourceKey<LootTable>, LootTable.Builder> lootTable) {
        HolderLookup.Provider wrapperLookup;

        try {
            wrapperLookup = registryLookup.get();
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }

        lootTable.accept(ModLootTables.LEVEL_0_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(Items.POISONOUS_POTATO))
            .add(LootItem.lootTableItem(Items.SPIDER_EYE))
            .add(LootItem.lootTableItem(Items.BAKED_POTATO))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.WOODEN_SWORD))
            .add(LootItem.lootTableItem(Items.WOODEN_AXE))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.CHAINMAIL_HELMET))
            .add(LootItem.lootTableItem(Items.CHAINMAIL_BOOTS))
            .add(LootItem.lootTableItem(Items.LEATHER_LEGGINGS))
            .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE))
          )
        );

        lootTable.accept(ModLootTables.LEVEL_0_UNCOMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.POISONOUS_POTATO))
            .add(LootItem.lootTableItem(Items.BAKED_POTATO)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 7f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.IRON_SWORD))
            .add(LootItem.lootTableItem(Items.STONE_AXE))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_HELMET))
            .add(LootItem.lootTableItem(Items.IRON_BOOTS))
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS))
            .add(LootItem.lootTableItem(Items.CHAINMAIL_CHESTPLATE))
            .add(LootItem.lootTableItem(Items.SHIELD))
          )
        );

        lootTable.accept(ModLootTables.LEVEL_0_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(ConstantValue.exactly(1f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 4f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(Items.BAKED_POTATO)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
            )
            .add(LootItem.lootTableItem(Items.COOKED_CHICKEN)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_SWORD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_SWORD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_AXE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_BOOTS))
            .add(LootItem.lootTableItem(Items.DIAMOND_HELMET))
          )
        );

        lootTable.accept(ModLootTables.LEVEL_0_EPIC, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(3f, 5f))
            .add(LootItem.lootTableItem(Items.BAKED_POTATO)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 14f)))
            )
            .add(LootItem.lootTableItem(Items.COOKED_CHICKEN)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 6f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.DIAMOND_SWORD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_AXE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(0))
            )
          )
        );


        lootTable.accept(ModLootTables.LEVEL_1_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 5f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(ConstantValue.exactly(3f))
            .add(LootItem.lootTableItem(Items.COOKED_BEEF)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 8f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.BUNDLE))
            .add(LootItem.lootTableItem(Items.WHITE_BUNDLE))
            .add(LootItem.lootTableItem(Items.ORANGE_BUNDLE))
            .add(LootItem.lootTableItem(Items.MAGENTA_BUNDLE))
            .add(LootItem.lootTableItem(Items.LIGHT_BLUE_BUNDLE))
            .add(LootItem.lootTableItem(Items.YELLOW_BUNDLE))
            .add(LootItem.lootTableItem(Items.LIME_BUNDLE))
            .add(LootItem.lootTableItem(Items.PINK_BUNDLE))
            .add(LootItem.lootTableItem(Items.GRAY_BUNDLE))
            .add(LootItem.lootTableItem(Items.LIGHT_GRAY_BUNDLE))
            .add(LootItem.lootTableItem(Items.CYAN_BUNDLE))
            .add(LootItem.lootTableItem(Items.PURPLE_BUNDLE))
            .add(LootItem.lootTableItem(Items.BLUE_BUNDLE))
            .add(LootItem.lootTableItem(Items.BROWN_BUNDLE))
            .add(LootItem.lootTableItem(Items.GREEN_BUNDLE))
            .add(LootItem.lootTableItem(Items.RED_BUNDLE))
            .add(LootItem.lootTableItem(Items.BLACK_BUNDLE))

            .add(LootItem.lootTableItem(Items.FISHING_ROD))
            .add(LootItem.lootTableItem(Items.CLOCK))
            .add(LootItem.lootTableItem(Items.SPYGLASS))
            .add(LootItem.lootTableItem(Items.COMPASS))
            .add(LootItem.lootTableItem(Items.RECOVERY_COMPASS))

            .add(LootItem.lootTableItem(Items.TORCH))
            .add(LootItem.lootTableItem(Items.SOUL_TORCH))
            .add(LootItem.lootTableItem(Items.LANTERN))
            .add(LootItem.lootTableItem(Items.SOUL_LANTERN))

            .add(LootItem.lootTableItem(Items.WIND_CHARGE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.IRON_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
        );

        lootTable.accept(ModLootTables.LEVEL_1_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 11f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.COOKED_BEEF)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 20f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE))
          )
          .withPool(LootPool.lootPool()
            .setRolls(ConstantValue.exactly(1f))
            .add(LootItem.lootTableItem(Items.TORCH))
            .add(LootItem.lootTableItem(Items.SOUL_TORCH))
            .add(LootItem.lootTableItem(Items.LANTERN))
            .add(LootItem.lootTableItem(Items.SOUL_LANTERN))

            .add(LootItem.lootTableItem(Items.ENDER_PEARL))

            .add(LootItem.lootTableItem(Items.WIND_CHARGE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 24f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(1))
            )
          )
        );


        lootTable.accept(ModLootTables.LEVEL_2_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 3f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 4f))
            .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.BAKED_POTATO))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.BUNDLE))
            .add(LootItem.lootTableItem(Items.FISHING_ROD))
            .add(LootItem.lootTableItem(Items.CLOCK))
            .add(LootItem.lootTableItem(Items.SPYGLASS))
            .add(LootItem.lootTableItem(Items.COMPASS))
            .add(LootItem.lootTableItem(Items.RECOVERY_COMPASS))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.BUCKET))
            .add(LootItem.lootTableItem(Items.WATER_BUCKET))
            .add(LootItem.lootTableItem(Items.PUFFERFISH_BUCKET))
            .add(LootItem.lootTableItem(Items.SALMON_BUCKET))
            .add(LootItem.lootTableItem(Items.COD_BUCKET))
            .add(LootItem.lootTableItem(Items.TROPICAL_FISH_BUCKET))
            .add(LootItem.lootTableItem(Items.AXOLOTL_BUCKET))
            .add(LootItem.lootTableItem(Items.TADPOLE_BUCKET))

            .add(LootItem.lootTableItem(Items.TORCH))
            .add(LootItem.lootTableItem(Items.SOUL_TORCH))
            .add(LootItem.lootTableItem(Items.LANTERN))
            .add(LootItem.lootTableItem(Items.SOUL_LANTERN))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.WATER))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_BOOTS))
            .add(LootItem.lootTableItem(Items.IRON_HELMET))
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS))
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE))
          )
        );

        lootTable.accept(ModLootTables.LEVEL_2_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 3f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 4f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f))
              )
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.BUNDLE))
            .add(LootItem.lootTableItem(Items.FISHING_ROD))
            .add(LootItem.lootTableItem(Items.CLOCK))
            .add(LootItem.lootTableItem(Items.SPYGLASS))
            .add(LootItem.lootTableItem(Items.COMPASS))
            .add(LootItem.lootTableItem(Items.RECOVERY_COMPASS))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.RAW_IRON))
            .add(LootItem.lootTableItem(Items.RAW_COPPER))
            .add(LootItem.lootTableItem(Items.RAW_GOLD))
            .add(LootItem.lootTableItem(Items.ANCIENT_DEBRIS))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 4f))
            .add(LootItem.lootTableItem(Items.BUCKET))
            .add(LootItem.lootTableItem(Items.WATER_BUCKET))
            .add(LootItem.lootTableItem(Items.PUFFERFISH_BUCKET))
            .add(LootItem.lootTableItem(Items.SALMON_BUCKET))
            .add(LootItem.lootTableItem(Items.COD_BUCKET))
            .add(LootItem.lootTableItem(Items.TROPICAL_FISH_BUCKET))
            .add(LootItem.lootTableItem(Items.AXOLOTL_BUCKET))
            .add(LootItem.lootTableItem(Items.TADPOLE_BUCKET))

            .add(LootItem.lootTableItem(Items.TORCH))
            .add(LootItem.lootTableItem(Items.SOUL_TORCH))
            .add(LootItem.lootTableItem(Items.LANTERN))
            .add(LootItem.lootTableItem(Items.SOUL_LANTERN))

            .add(LootItem.lootTableItem(Items.ENDER_PEARL))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 3f))
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.WATER))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.IRON_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_BOOTS)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_HELMET)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_LEGGINGS)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND_CHESTPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(2))
            )
          )
        );


        lootTable.accept(ModLootTables.LEVEL_3_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.COBWEB))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.BAKED_POTATO))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(2f, 3f))
            .add(LootItem.lootTableItem(Items.REDSTONE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.REPEATER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.COMPARATOR)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.OBSERVER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.PISTON)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.DRIED_KELP))
            .add(LootItem.lootTableItem(Items.DRIED_KELP))
            .add(LootItem.lootTableItem(Items.DRIED_KELP))
            .add(LootItem.lootTableItem(Items.DRIED_KELP))
            .add(LootItem.lootTableItem(Items.DRIED_KELP_BLOCK))

            .add(LootItem.lootTableItem(Items.RAW_IRON))
            .add(LootItem.lootTableItem(Items.RAW_COPPER))
            .add(LootItem.lootTableItem(Items.RAW_GOLD))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.WATER))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.AWKWARD))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.SPIDER_EYE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.FERMENTED_SPIDER_EYE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SUGAR)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.RABBIT_FOOT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.GLISTERING_MELON_SLICE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.GHAST_TEAR)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.MAGMA_CREAM)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.PUFFERFISH)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.TURTLE_SCUTE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.TURTLE_HELMET)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.PHANTOM_MEMBRANE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.BREEZE_ROD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.COBWEB)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SLIME_BALL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SLIME_BLOCK)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.STONE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.FIRE_RESISTANCE))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.LONG_FIRE_RESISTANCE))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.LONG_STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.LONG_SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.LONG_REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_TURTLE_MASTER))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.TURTLE_MASTER))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.LONG_TURTLE_MASTER))
            )

            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.FIRE_RESISTANCE))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.LONG_FIRE_RESISTANCE))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.LONG_STRENGTH))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.LONG_SWIFTNESS))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.LONG_REGENERATION))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.STRONG_TURTLE_MASTER))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.TURTLE_MASTER))
            )
            .add(LootItem.lootTableItem(Items.SPLASH_POTION)
              .apply(potion(wrapperLookup, Potions.LONG_TURTLE_MASTER))
            )
          )
        );

        lootTable.accept(ModLootTables.LEVEL_3_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(ModItems.ALMOND_WATTER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 11f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.COOKED_BEEF)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 20f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(Items.GLOWSTONE_DUST)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 16f)))
            )
            .add(LootItem.lootTableItem(Items.REDSTONE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 16f)))
            )
            .add(LootItem.lootTableItem(Items.GUNPOWDER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.NETHER_WART)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 16f)))
            )
            .add(LootItem.lootTableItem(Items.GLASS_BOTTLE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.BLAZE_POWDER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.DRIED_KELP_BLOCK))
            .add(LootItem.lootTableItem(Items.RAW_IRON))
            .add(LootItem.lootTableItem(Items.RAW_COPPER))
            .add(LootItem.lootTableItem(Items.RAW_GOLD))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.WATER))
            )
            .add(LootItem.lootTableItem(Items.POTION)
              .apply(potion(wrapperLookup, Potions.AWKWARD))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.SPIDER_EYE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.FERMENTED_SPIDER_EYE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.SUGAR)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.RABBIT_FOOT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.GLISTERING_MELON_SLICE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.GHAST_TEAR)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.MAGMA_CREAM)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.PUFFERFISH)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.TURTLE_SCUTE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.TURTLE_HELMET)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.PHANTOM_MEMBRANE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.BREEZE_ROD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.COBWEB)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.SLIME_BALL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.SLIME_BLOCK)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.STONE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(3))
            )
          )
        );


        lootTable.accept(ModLootTables.LEVEL_4_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(2f, 5f))
            .add(LootItem.lootTableItem(Items.PAPER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.INK_SAC)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.FEATHER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.BOOK)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.BOOKSHELF)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.WRITABLE_BOOK))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 2f))
            .add(LootItem.lootTableItem(Items.COAL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
            )
            .add(LootItem.lootTableItem(Items.CHARCOAL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
            )
            .add(LootItem.lootTableItem(Items.STRING)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
            )
            .add(LootItem.lootTableItem(Items.RAW_IRON)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.RAW_COPPER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
            )
          )
        );

        lootTable.accept(ModLootTables.LEVEL_4_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(2f, 5f))
            .add(LootItem.lootTableItem(Items.BOOK)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 16f)))
            )
            .add(LootItem.lootTableItem(Items.BOOKSHELF)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.WRITABLE_BOOK))
            .add(LootItem.lootTableItem(Items.BOOK)
              .apply(EnchantWithLevelsFunction.enchantWithLevels(wrapperLookup, UniformGenerator.between(10f, 30f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 4f))
            .add(LootItem.lootTableItem(Items.COAL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
            )
            .add(LootItem.lootTableItem(Items.CHARCOAL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
            )
            .add(LootItem.lootTableItem(Items.STRING)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
            )
            .add(LootItem.lootTableItem(Items.RAW_IRON)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
            )
            .add(LootItem.lootTableItem(Items.RAW_COPPER)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
            )
            .add(LootItem.lootTableItem(Items.RAW_GOLD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
            )
            .add(LootItem.lootTableItem(Items.ENDER_PEARL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE))
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.COAST_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.WILD_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.WARD_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.EYE_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.VEX_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.RIB_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.HOST_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
            .add(LootItem.lootTableItem(Items.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(4))
            )
          )
        );

        lootTable.accept(ModLootTables.LEVEL_4_LUCKY_O_MILK, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(2f, 16f))
            .add(LootItem.lootTableItem(ModItems.COLD_PLAIN_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_PLAIN_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_PLAIN_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_PLAIN_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_PLAIN_LUCKY_O_MILK))

            .add(LootItem.lootTableItem(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))

            .add(LootItem.lootTableItem(ModItems.COLD_CHOCO_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_CHOCO_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_CHOCO_LUCKY_O_MILK))

            .add(LootItem.lootTableItem(ModItems.COLD_MATCHA_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_MATCHA_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_MATCHA_LUCKY_O_MILK))

            .add(LootItem.lootTableItem(ModItems.COLD_BANANA_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_BANANA_LUCKY_O_MILK))
            .add(LootItem.lootTableItem(ModItems.COLD_BANANA_LUCKY_O_MILK))

            .add(LootItem.lootTableItem(ModItems.COLD_LUCK_LUCKY_O_MILK))
          )
        );


        lootTable.accept(ModLootTables.LEVEL_5_COMMON, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 4f))
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE))
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE))
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE))
            .add(LootItem.lootTableItem(Items.DIAMOND)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.EMERALD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_BOOTS)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_HELMET)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 1f))
            .add(LootItem.lootTableItem(Items.IRON_SWORD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_AXE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_SHOVEL)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_HOE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
        );

        lootTable.accept(ModLootTables.LEVEL_5_RARE, LootTable.lootTable()
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(1f, 8f))
            .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.DIAMOND)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.EMERALD)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 8f)))
            )
            .add(LootItem.lootTableItem(Items.ENCHANTED_GOLDEN_APPLE)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.TOTEM_OF_UNDYING)
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.SHIELD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_BOOTS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_HELMET)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_LEGGINGS)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_CHESTPLATE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .setRolls(UniformGenerator.between(0f, 2f))
            .add(LootItem.lootTableItem(Items.IRON_SWORD)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_AXE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_SHOVEL)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
            .add(LootItem.lootTableItem(Items.IRON_HOE)
              .apply(EnchantRandomlyFunction.randomApplicableEnchantment(wrapperLookup))
              .apply(SetItemCountFunction.setCount(UniformGenerator.between(0f, 1f)))
            )
          )
          .withPool(LootPool.lootPool()
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(EmptyLootItem.emptyItem())
            .add(LootItem.lootTableItem(ModItems.LEVEL_KEY)
              .apply(levelKeyData(5))
            )
          )
        );
    }

    private net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.Builder potion(HolderLookup.Provider wrapperLookup, Holder<Potion> entry) {
        return SetPotionFunction.setPotion(wrapperLookup.getOrThrow(entry.unwrapKey().orElseThrow()));
    }


    @SuppressWarnings("deprecation")
    private net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.Builder levelKeyData(final int levelNumber) {
        return SetCustomDataFunction.setCustomData(LevelKeyItem.ofLevel(BackroomsHandler.getLevelId(levelNumber)));
    }
}
