package net.fawnoculus.vanillaBackrooms.client.datagen.loot;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableProvider;
import net.fawnoculus.vanillaBackrooms.items.ModItems;
import net.fawnoculus.vanillaBackrooms.misc.ModLootTables;
import net.minecraft.item.Items;
import net.minecraft.loot.LootPool;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.context.LootContextTypes;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.*;
import net.minecraft.loot.provider.number.ConstantLootNumberProvider;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;
import net.minecraft.potion.Potion;
import net.minecraft.potion.Potions;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.entry.RegistryEntry;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.function.BiConsumer;

public class ChestLootTableProvider extends SimpleFabricLootTableProvider {
	private final CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup;

	public ChestLootTableProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
		super(output, registryLookup, LootContextTypes.CHEST);

		this.registryLookup = registryLookup;
	}

	@Override
	public void accept(BiConsumer<RegistryKey<LootTable>, LootTable.Builder> lootTable) {
		RegistryWrapper.WrapperLookup wrapperLookup;

		try {
			wrapperLookup = registryLookup.get();
		} catch (InterruptedException | ExecutionException e) {
			throw new RuntimeException(e);
		}

		lootTable.accept(ModLootTables.LEVEL_0_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(Items.POISONOUS_POTATO))
			.with(ItemEntry.builder(Items.SPIDER_EYE))
			.with(ItemEntry.builder(Items.BAKED_POTATO))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.WOODEN_SWORD))
			.with(ItemEntry.builder(Items.WOODEN_AXE))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.CHAINMAIL_HELMET))
			.with(ItemEntry.builder(Items.CHAINMAIL_BOOTS))
			.with(ItemEntry.builder(Items.LEATHER_LEGGINGS))
			.with(ItemEntry.builder(Items.LEATHER_CHESTPLATE))
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_0_UNCOMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.POISONOUS_POTATO))
			.with(ItemEntry.builder(Items.BAKED_POTATO)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 7f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.IRON_SWORD))
			.with(ItemEntry.builder(Items.STONE_AXE))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_HELMET))
			.with(ItemEntry.builder(Items.IRON_BOOTS))
			.with(ItemEntry.builder(Items.IRON_LEGGINGS))
			.with(ItemEntry.builder(Items.CHAINMAIL_CHESTPLATE))
			.with(ItemEntry.builder(Items.SHIELD))
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_0_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(ConstantLootNumberProvider.create(1f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 4f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(Items.BAKED_POTATO)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 5f)))
			)
			.with(ItemEntry.builder(Items.COOKED_CHICKEN)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 3f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_SWORD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_SWORD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_AXE)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_BOOTS))
			.with(ItemEntry.builder(Items.DIAMOND_HELMET))
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_0_EPIC, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(3f, 5f))
			.with(ItemEntry.builder(Items.BAKED_POTATO)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 14f)))
			)
			.with(ItemEntry.builder(Items.COOKED_CHICKEN)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 6f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_CARROT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 3f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.DIAMOND_SWORD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_AXE)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		);


		lootTable.accept(ModLootTables.LEVEL_1_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 5f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(ConstantLootNumberProvider.create(3f))
			.with(ItemEntry.builder(Items.COOKED_BEEF)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 8f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.BUNDLE))
			.with(ItemEntry.builder(Items.WHITE_BUNDLE))
			.with(ItemEntry.builder(Items.ORANGE_BUNDLE))
			.with(ItemEntry.builder(Items.MAGENTA_BUNDLE))
			.with(ItemEntry.builder(Items.LIGHT_BLUE_BUNDLE))
			.with(ItemEntry.builder(Items.YELLOW_BUNDLE))
			.with(ItemEntry.builder(Items.LIME_BUNDLE))
			.with(ItemEntry.builder(Items.PINK_BUNDLE))
			.with(ItemEntry.builder(Items.GRAY_BUNDLE))
			.with(ItemEntry.builder(Items.LIGHT_GRAY_BUNDLE))
			.with(ItemEntry.builder(Items.CYAN_BUNDLE))
			.with(ItemEntry.builder(Items.PURPLE_BUNDLE))
			.with(ItemEntry.builder(Items.BLUE_BUNDLE))
			.with(ItemEntry.builder(Items.BROWN_BUNDLE))
			.with(ItemEntry.builder(Items.GREEN_BUNDLE))
			.with(ItemEntry.builder(Items.RED_BUNDLE))
			.with(ItemEntry.builder(Items.BLACK_BUNDLE))

			.with(ItemEntry.builder(Items.FISHING_ROD))
			.with(ItemEntry.builder(Items.CLOCK))
			.with(ItemEntry.builder(Items.SPYGLASS))
			.with(ItemEntry.builder(Items.COMPASS))
			.with(ItemEntry.builder(Items.RECOVERY_COMPASS))

			.with(ItemEntry.builder(Items.TORCH))
			.with(ItemEntry.builder(Items.SOUL_TORCH))
			.with(ItemEntry.builder(Items.LANTERN))
			.with(ItemEntry.builder(Items.SOUL_LANTERN))

			.with(ItemEntry.builder(Items.WIND_CHARGE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_1_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(3f, 11f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.COOKED_BEEF)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(4f, 20f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_CARROT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_APPLE))
		  )
		  .pool(LootPool.builder()
			.rolls(ConstantLootNumberProvider.create(1f))
			.with(ItemEntry.builder(Items.TORCH))
			.with(ItemEntry.builder(Items.SOUL_TORCH))
			.with(ItemEntry.builder(Items.LANTERN))
			.with(ItemEntry.builder(Items.SOUL_LANTERN))

			.with(ItemEntry.builder(Items.ENDER_PEARL))

			.with(ItemEntry.builder(Items.WIND_CHARGE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 24f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		);


		lootTable.accept(ModLootTables.LEVEL_2_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 3f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 4f))
			.with(ItemEntry.builder(Items.ROTTEN_FLESH)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.BAKED_POTATO))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.BUNDLE))
			.with(ItemEntry.builder(Items.FISHING_ROD))
			.with(ItemEntry.builder(Items.CLOCK))
			.with(ItemEntry.builder(Items.SPYGLASS))
			.with(ItemEntry.builder(Items.COMPASS))
			.with(ItemEntry.builder(Items.RECOVERY_COMPASS))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.BUCKET))
			.with(ItemEntry.builder(Items.WATER_BUCKET))
			.with(ItemEntry.builder(Items.PUFFERFISH_BUCKET))
			.with(ItemEntry.builder(Items.SALMON_BUCKET))
			.with(ItemEntry.builder(Items.COD_BUCKET))
			.with(ItemEntry.builder(Items.TROPICAL_FISH_BUCKET))
			.with(ItemEntry.builder(Items.AXOLOTL_BUCKET))
			.with(ItemEntry.builder(Items.TADPOLE_BUCKET))

			.with(ItemEntry.builder(Items.TORCH))
			.with(ItemEntry.builder(Items.SOUL_TORCH))
			.with(ItemEntry.builder(Items.LANTERN))
			.with(ItemEntry.builder(Items.SOUL_LANTERN))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.WATER))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_BOOTS))
			.with(ItemEntry.builder(Items.IRON_HELMET))
			.with(ItemEntry.builder(Items.IRON_LEGGINGS))
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE))
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_2_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 3f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 4f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f))
			  )
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.BUNDLE))
			.with(ItemEntry.builder(Items.FISHING_ROD))
			.with(ItemEntry.builder(Items.CLOCK))
			.with(ItemEntry.builder(Items.SPYGLASS))
			.with(ItemEntry.builder(Items.COMPASS))
			.with(ItemEntry.builder(Items.RECOVERY_COMPASS))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.RAW_IRON))
			.with(ItemEntry.builder(Items.RAW_COPPER))
			.with(ItemEntry.builder(Items.RAW_GOLD))
			.with(ItemEntry.builder(Items.ANCIENT_DEBRIS))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 4f))
			.with(ItemEntry.builder(Items.BUCKET))
			.with(ItemEntry.builder(Items.WATER_BUCKET))
			.with(ItemEntry.builder(Items.PUFFERFISH_BUCKET))
			.with(ItemEntry.builder(Items.SALMON_BUCKET))
			.with(ItemEntry.builder(Items.COD_BUCKET))
			.with(ItemEntry.builder(Items.TROPICAL_FISH_BUCKET))
			.with(ItemEntry.builder(Items.AXOLOTL_BUCKET))
			.with(ItemEntry.builder(Items.TADPOLE_BUCKET))

			.with(ItemEntry.builder(Items.TORCH))
			.with(ItemEntry.builder(Items.SOUL_TORCH))
			.with(ItemEntry.builder(Items.LANTERN))
			.with(ItemEntry.builder(Items.SOUL_LANTERN))

			.with(ItemEntry.builder(Items.ENDER_PEARL))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 3f))
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.WATER))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_BOOTS)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_HELMET)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_LEGGINGS)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.DIAMOND_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.DIAMOND_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.DIAMOND_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.DIAMOND_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		);


		lootTable.accept(ModLootTables.LEVEL_3_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.COBWEB))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(Items.ROTTEN_FLESH)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.BAKED_POTATO))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(2f, 3f))
			.with(ItemEntry.builder(Items.REDSTONE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.REPEATER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.COMPARATOR)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.OBSERVER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.PISTON)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.DRIED_KELP))
			.with(ItemEntry.builder(Items.DRIED_KELP))
			.with(ItemEntry.builder(Items.DRIED_KELP))
			.with(ItemEntry.builder(Items.DRIED_KELP))
			.with(ItemEntry.builder(Items.DRIED_KELP_BLOCK))

			.with(ItemEntry.builder(Items.RAW_IRON))
			.with(ItemEntry.builder(Items.RAW_COPPER))
			.with(ItemEntry.builder(Items.RAW_GOLD))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.WATER))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.AWKWARD))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.SPIDER_EYE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.FERMENTED_SPIDER_EYE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SUGAR)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.RABBIT_FOOT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.GLISTERING_MELON_SLICE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.GHAST_TEAR)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.MAGMA_CREAM)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.PUFFERFISH)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_CARROT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.TURTLE_SCUTE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.TURTLE_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.PHANTOM_MEMBRANE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.BREEZE_ROD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.COBWEB)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SLIME_BALL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SLIME_BLOCK)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.STONE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.FIRE_RESISTANCE))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_FIRE_RESISTANCE))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_STRENGTH))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.STRENGTH))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_STRENGTH))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_REGENERATION))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.REGENERATION))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_REGENERATION))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_TURTLE_MASTER))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.TURTLE_MASTER))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_TURTLE_MASTER))
			)

			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.FIRE_RESISTANCE))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_FIRE_RESISTANCE))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_STRENGTH))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.STRENGTH))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_STRENGTH))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_SWIFTNESS))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_REGENERATION))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.REGENERATION))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_REGENERATION))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.STRONG_TURTLE_MASTER))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.TURTLE_MASTER))
			)
			.with(ItemEntry.builder(Items.SPLASH_POTION)
			  .apply(potion(wrapperLookup, Potions.LONG_TURTLE_MASTER))
			)
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_3_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(ModItems.ALMOND_WATTER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(3f, 11f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.COOKED_BEEF)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(4f, 20f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_CARROT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_APPLE))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(Items.GLOWSTONE_DUST)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 16f)))
			)
			.with(ItemEntry.builder(Items.REDSTONE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 16f)))
			)
			.with(ItemEntry.builder(Items.GUNPOWDER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.NETHER_WART)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(4f, 16f)))
			)
			.with(ItemEntry.builder(Items.GLASS_BOTTLE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 8f)))
			)
			.with(ItemEntry.builder(Items.BLAZE_POWDER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 8f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.DRIED_KELP_BLOCK))
			.with(ItemEntry.builder(Items.RAW_IRON))
			.with(ItemEntry.builder(Items.RAW_COPPER))
			.with(ItemEntry.builder(Items.RAW_GOLD))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.WATER))
			)
			.with(ItemEntry.builder(Items.POTION)
			  .apply(potion(wrapperLookup, Potions.AWKWARD))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.SPIDER_EYE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.FERMENTED_SPIDER_EYE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.SUGAR)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.RABBIT_FOOT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.GLISTERING_MELON_SLICE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.GHAST_TEAR)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.MAGMA_CREAM)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.PUFFERFISH)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.GOLDEN_CARROT)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.TURTLE_SCUTE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.TURTLE_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.PHANTOM_MEMBRANE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.BREEZE_ROD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.COBWEB)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.SLIME_BALL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.SLIME_BLOCK)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
			.with(ItemEntry.builder(Items.STONE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 4f)))
			)
		  )
		);


		lootTable.accept(ModLootTables.LEVEL_4_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(2f, 5f))
			.with(ItemEntry.builder(Items.PAPER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.INK_SAC)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.FEATHER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.BOOK)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.BOOKSHELF)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.WRITABLE_BOOK))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 2f))
			.with(ItemEntry.builder(Items.COAL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 6f)))
			)
			.with(ItemEntry.builder(Items.CHARCOAL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 6f)))
			)
			.with(ItemEntry.builder(Items.STRING)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 3f)))
			)
			.with(ItemEntry.builder(Items.RAW_IRON)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.RAW_COPPER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 5f)))
			)
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_4_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(2f, 5f))
			.with(ItemEntry.builder(Items.BOOK)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 16f)))
			)
			.with(ItemEntry.builder(Items.BOOKSHELF)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.WRITABLE_BOOK))
			.with(ItemEntry.builder(Items.BOOK)
			  .apply(EnchantWithLevelsLootFunction.builder(wrapperLookup, UniformLootNumberProvider.create(10f, 30f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 4f))
			.with(ItemEntry.builder(Items.COAL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 6f)))
			)
			.with(ItemEntry.builder(Items.CHARCOAL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(2f, 6f)))
			)
			.with(ItemEntry.builder(Items.STRING)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 3f)))
			)
			.with(ItemEntry.builder(Items.RAW_IRON)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 4f)))
			)
			.with(ItemEntry.builder(Items.RAW_COPPER)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 5f)))
			)
			.with(ItemEntry.builder(Items.RAW_GOLD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 3f)))
			)
			.with(ItemEntry.builder(Items.ENDER_PEARL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE))
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.COAST_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.WILD_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.WARD_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.EYE_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.VEX_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.RIB_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.HOST_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
			.with(ItemEntry.builder(Items.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 2f)))
			)
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_4_LUCKY_O_MILK, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(2f, 16f))
			.with(ItemEntry.builder(ModItems.COLD_PLAIN_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_PLAIN_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_PLAIN_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_PLAIN_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_PLAIN_LUCKY_O_MILK))

			.with(ItemEntry.builder(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_STRAWBERRY_LUCKY_O_MILK))

			.with(ItemEntry.builder(ModItems.COLD_CHOCO_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_CHOCO_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_CHOCO_LUCKY_O_MILK))

			.with(ItemEntry.builder(ModItems.COLD_MATCHA_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_MATCHA_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_MATCHA_LUCKY_O_MILK))

			.with(ItemEntry.builder(ModItems.COLD_BANANA_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_BANANA_LUCKY_O_MILK))
			.with(ItemEntry.builder(ModItems.COLD_BANANA_LUCKY_O_MILK))

			.with(ItemEntry.builder(ModItems.COLD_LUCK_LUCKY_O_MILK))
		  )
		);


		lootTable.accept(ModLootTables.LEVEL_5_COMMON, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 4f))
			.with(ItemEntry.builder(Items.GOLDEN_APPLE))
			.with(ItemEntry.builder(Items.GOLDEN_APPLE))
			.with(ItemEntry.builder(Items.GOLDEN_APPLE))
			.with(ItemEntry.builder(Items.DIAMOND)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.EMERALD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 1f))
			.with(ItemEntry.builder(Items.IRON_SWORD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_AXE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_SHOVEL)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_HOE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		);

		lootTable.accept(ModLootTables.LEVEL_5_RARE, LootTable.builder()
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(1f, 8f))
			.with(ItemEntry.builder(Items.GOLDEN_APPLE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.DIAMOND)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.EMERALD)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(1f, 8f)))
			)
			.with(ItemEntry.builder(Items.ENCHANTED_GOLDEN_APPLE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.TOTEM_OF_UNDYING)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.SHIELD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_BOOTS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_HELMET)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_LEGGINGS)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
			.with(ItemEntry.builder(Items.IRON_CHESTPLATE)
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			)
		  )
		  .pool(LootPool.builder()
			.rolls(UniformLootNumberProvider.create(0f, 2f))
			.with(ItemEntry.builder(Items.IRON_SWORD)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_AXE)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_SHOVEL)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
			.with(ItemEntry.builder(Items.IRON_HOE)
			  .apply(EnchantRandomlyLootFunction.builder(wrapperLookup))
			  .apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(0f, 1f)))
			)
		  )
		);
	}

	private SetPotionLootFunction.Builder<?> potion(RegistryWrapper.WrapperLookup wrapperLookup, RegistryEntry<Potion> entry) {
		return SetPotionLootFunction.builder(wrapperLookup.getEntryOrThrow(entry.getKey().orElseThrow()));
	}
}
